### ISSUE TITLE
خطا آدرس کتاب آموزش گیت

### ISSUE THREAD

**Issue by ebadola** [dariubs/git#34]
آدرس زیر دارای خطا هست لطفا بررسی کنید
http://git.coderz.ir/en/latest/book/

خطا:
Error 1014

**Comment by Mehraban** [comment]
سلام

کماکان خطای زیر موجود است


```
Error 1014 Ray ID: 46a2dc2a94e3c297 • 2018-10-15 14:08:50 UTC
CNAME Cross-User Banned

```

**Comment by dariubs** [comment]
دامنه‌ی قبلی مشکلاتی داشت که متاسفانه موفق به حلش نشدیم. از حالا در آدرس جدید این کتاب در دسترس شماست :
http://git.codecast.ir

**Comment by sajadshokri** [comment]
@dariubs 
Link Updated in Coderz Post
