### ISSUE TITLE
using several git programs simultaneously

### ISSUE THREAD

**Issue by AtomicNess123** [dariubs/git#35]
I have a question of a basic nature. I was working with SourceTree in a local repo pushing to Github.com. At some point I decided to use Github Desktop, so I added the local repo and started to push to Github.com. I did not like this software, so I went back to SourceTree. Opened my project there but changes were not being tracked anymore. I wonder if one can use two git managers for tracking changes or else I don't know what went wrong.

**Comment by sajadshokri** [comment]
the only software managing your Repo is Git, so you should consider that apps like SourceTree, Github Desktop, Git Kraken, or anything else are just wrappers to provide easier approach.

to find what has happened, first check the branch `git rev-parse --abbrev-ref HEAD`
then the status: `git status`
check the commit logs `git log`
or any other check you find online
try using git commands and you will never face any problem...
