### ISSUE TITLE
راهنمایی برای نحوه استفاده

### ISSUE THREAD

**Issue by saghian** [dariubs/git#5]
سلام دوست عزیز
چگونه میتوانم از آموزش شما استفاده کنم ؟
خروجی پی دی اف می دهد یا اچ تی ام ال ؟
ممنون میشوم راهنمایی بفرمایی

**Comment by dariubs** [comment]
سلام این پروژه هم اکنون در حال توسعه است
بعد از تکمیل اولین نسخه خروجی های قابل استفاده در اختیار همه قرار خواهد گرفت.
